defaults:
  - data_processing_config_schema

  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

# data version provided. The other parameters are provided via the 
# `data_processing_config_schema` these are not likely to change
# (e.g. remote repository)
version: v8
